<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class pelicula extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pelicula')->insert([
            [
                'id' => 1,
                'adult' => false,
                'backdrop_ruta' => '/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg',
                'id_api' => 986056,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Thunderbolts*',
                'sinopsis' => 'Un grupo de supervillanos y antihéroes van en misiones para el gobierno. Basado en la serie de cómics del mismo nombre.',
                'poster_ruta' => '/zLbhKNJGDSfBCXFNtypM7ZuPTaW.jpg',
                'fecha_estreno' => '2025-04-30',
                'titulo' => 'Thunderbolts*',
                'video' => false,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::now(),
                'duracion' => 120,
                'puntuacion_promedio' => 7.5,
                'numero_votos' => 1500,
                'popularidad' => 123.45,
            ],
            [
                'id' => 2,
                'adult' => false,
                'backdrop_ruta' => '/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg',
                'id_api' => 1197306,
                'lenguaje_original' => 'en',
                'titulo_original' => 'A Working Man',
                'sinopsis' => 'Levon Cade dejó atrás una condecorada carrera militar en las operaciones encubiertas para vivir una vida sencilla trabajando en la construcción. Pero cuando la hija de su jefe, que para él es como de la familia, es secuestrada por traficantes de personas, su búsqueda para traerla a casa descubre un mundo de corrupción mucho mayor de lo que jamás podría haber imaginado.',
                'poster_ruta' => '/oCsn3MV3QOJWnGVCb8B8VWrX5Qp.jpg',
                'fecha_estreno' => '2025-03-26',
                'titulo' => 'A Working Man',
                'video' => false,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::now(),
                'duracion' => 95,
                'puntuacion_promedio' => 6.8,
                'numero_votos' => 500,
                'popularidad' => 55.67,
            ],
            [
                'id' => 3,
                'adult' => false,
                'backdrop_ruta' => '/44YfHklKam8COMUxDZop2Lnp0CS.jpg',
                'id_api' => 668489,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Havoc',
                'sinopsis' => 'Cuando un robo de drogas tiene consecuencias fatales, un policía lucha contra el submundo criminal de una ciudad corrupta para salvar al hijo de un político.',
                'poster_ruta' => '/tbsDLmo2Ej8YFM0HKcOGfNMTlyJ.jpg',
                'fecha_estreno' => '2025-04-24',
                'titulo' => 'Estragos',
                'video' => false,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::now(),
                'duracion' => 110,
                'puntuacion_promedio' => 7.0,
                'numero_votos' => 800,
                'popularidad' => 88.99,
            ],
            [
                'id' => 4,
                'adult' => false,
                'backdrop_ruta' => '/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg',
                'id_api' => 950387,
                'lenguaje_original' => 'en',
                'titulo_original' => 'A Minecraft Movie',
                'sinopsis' => 'Cuatro inadaptados se encuentran luchando con problemas ordinarios cuando de repente se ven arrastrados a través de un misterioso portal al Mundo Exterior: un extraño país de las maravillas cúbico que se nutre de la imaginación. Para volver a casa, tendrán que dominar este mundo mientras se embarcan en una búsqueda mágica con un inesperado experto artesano, Steve.',
                'poster_ruta' => '/mFjtmmh4RtK9tLv1aPnUsl6st3m.jpg',
                'fecha_estreno' => '2025-03-31',
                'titulo' => 'Una película de Minecraft',
                'video' => false,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::now(),
                'duracion' => 90,
                'puntuacion_promedio' => 7.2,
                'numero_votos' => 1200,
                'popularidad' => 150.10,
            ],
            [
                'id' => 5,
                'adult' => false,
                'backdrop_ruta' => '/12tEzU0bNYKIjXXEwI5abuOotHF.jpg',
                'id_api' => 710258,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Rust',
                'sinopsis' => 'Harland Rust tiene la mala reputación de fuera de la ley despiadado, con precio por su cabeza. Cuando se entera de que su nieto de trece años ha sido condenado a la horca por un supuesto asesinato, decide viajar a Kansas. Después de un violento enfrentamiento, Rust consigue sacarlo de la prisión y huir hacia la frontera. Rust y su nieto tendrán que unir sus fuerzas para escapar del legendario mariscal Wood Helm y de un infame cazarrecompensas.',
                'poster_ruta' => '/tbJ3RkA2s6X5qrBzrYHYTxvDBui.jpg',
                'fecha_estreno' => '2025-05-01',
                'titulo' => 'Rust',
                'video' => false,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::now(),
                'duracion' => 105,
                'puntuacion_promedio' => 6.5,
                'numero_votos' => 300,
                'popularidad' => 40.20,
            ],
            [
                'id' => 6,
                'adult' => false,
                'backdrop_ruta' => '/bVm6udIB6iKsRqgMdQh6HywuEBj.jpg',
                'id_api' => 1233069,
                'lenguaje_original' => 'de',
                'titulo_original' => 'Exterritorial',
                'sinopsis' => 'Cuando su hijo desaparece en un consulado de EE. UU., una exsoldado de las fuerzas especiales hará lo imposible por encontrarlo... y destapará una oscura conspiración.',
                'poster_ruta' => '/7tWkxxiqraVx1IzYd4DHv6FIvhS.jpg',
                'fecha_estreno' => '2025-04-29',
                'titulo' => 'Extraterritorial',
                'video' => false,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::now(),
                'duracion' => 98,
                'puntuacion_promedio' => 7.1,
                'numero_votos' => 650,
                'popularidad' => 75.80,
            ],
        ]);
    }
}
